# Generated by Django 2.2.8 on 2020-07-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20200730_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
